twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        csrf_token_manager: '@security.csrf.token_manager'

when@test:
    twig:
        strict_variables: true
