controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fallback:
    path: /{path}
    controller: App\Controller\ServiceController::notFound
    requirements:
        path: .+
